### ISSUE TITLE
Add multi word parsing support

### ISSUE THREAD

**Issue by jjcard** [jjcard/TextAdventurePackage#1]
Currently parsing does word by word parsing (word being anything separated by spaces) , so an item like "Blue Book" would be parsed as two words. This means that if the command "Pick up Blue Book" was sent, the BasicTextParser wouldn't be able to correctly find that "Blue Book" was a object, even if it was in it's Dictionary. Better parsing is needed for Text adventure games.

So either BasicTextParser.java should be updated or a new Parser that implements ITextParser can be created.

the unit test multiWordTest in BasicTextParserTest.java gives an example on a simple use case that should  pass.

**Comment by ka1289** [comment]
Hi, can you provide some more details on the issue?

**Comment by jjcard** [comment]
Hi @ka1289, I realize the description was a little brief. I've updated it with a some more detail. If you have more specific questions, feel free to ask.

**Comment by b0n541** [comment]
I would like to take on that issue.
